### ISSUE TITLE
aclAuditor运行问题2

### ISSUE THREAD

**Issue by ztc19857** [cahi1l1yn/aclAuditor#2]
你好：
我已经配置好路径还是有报错
path = r'E:\\PycharmProjects\\venv\\Scripts\\file\\'
output = r'E:\\acl\\'

配置文件[111]开始审计
Traceback (most recent call last):
  File "E:/PycharmProjects/ACL/aclAuditor.py", line 403, in <module>
    main(path)
  File "E:/PycharmProjects/ACL/aclAuditor.py", line 358, in main
    acl_name = re.search(r'\w+$|\d+$',acl[0]).group()
NameError: name 're' is not defined

Process finished with exit code 1
请问这个问题如何解决呢

**Comment by cahi1l1yn** [comment]
NameError: name 're' is not defined
安装re模块
